# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0004_auto_20170414_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='users',
            new_name='owners',
        ),
        migrations.AlterField(
            model_name='alert',
            name='owners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='airquality.Rule'),
        ),
    ]
