# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0005_auto_20170414_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('received',)},
        ),
        migrations.AlterField(
            model_name='alert',
            name='owners',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
