# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0006_auto_20170414_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='owners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
