# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0007_auto_20170414_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='owners',
            field=models.CharField(max_length=30),
        ),
    ]
