# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airquality', '0008_auto_20170414_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='owners',
        ),
        migrations.AddField(
            model_name='alert',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
