# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0010_auto_20170414_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='owners',
            field=models.ManyToManyField(to='airquality.Person'),
        ),
    ]
