# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0011_auto_20170414_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='owners',
            field=models.ManyToManyField(related_name='user', to='airquality.Person'),
        ),
    ]
