# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0012_auto_20170414_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rule',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
