# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0013_auto_20170414_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
